### ISSUE TITLE
FEC 支持

### ISSUE THREAD

**Issue by oksbsb** [liudf0716/xkcptun#10]
与 kcptun 不兼容的主要问题是协议和 forward error correction 的问题，请问有支持的计划么

**Comment by liudf0716** [comment]
now  I am developing xfrp client project :
https://github.com/KunTengRom/xfrp
after finish that project,  I will solve kpctun-compatible problem.

**Comment by sudoconf** [comment]
@liudf0716 fec 支持 后面有计划吗
