### ISSUE TITLE
Ubuntu 14.04 LTS下编译完libevent2和json-c还需要加入下面3行

### ISSUE THREAD

**Issue by JollyTRjano** [liudf0716/xkcptun#12]
Hi Liu,
我在Ubuntu 14.04 LTS下server端编译完libevent2和json-c还需要加入下面3行才能运行：
ln -s /usr/local/lib/libevent-2.2.so.1 /usr/lib/libevent-2.2.so.1
ln -s /usr/local/lib/libevent-2.2.so.3 /usr/lib/libevent-2.2.so.3
ln -s /usr/local/lib/libjson-c.so.3 /usr/lib/libjson-c.so.3
我在跑youtube测试，配合ssr可以reach 10M-15Mbps左右。4k很勉强，2k没问题。有时会出现切换视频卡死，需要重启server端。大概是vps比较烂。
建议的话，希望直接在luci界面编辑client.json，这样比较方便2边参数同步，避免不必要的bug（我是把两边参数都配成一样再重启路由器运行的）。
Great thanks for your work!

**Comment by liudf0716** [comment]
@JollyTRjano u can use : 
ldconfig /usr/local

good suggestion, we will use command like kcptun to simplify xkcptun's implementation
