### ISSUE TITLE
传输大文件时效率没有kcptun-go好，只有几KB

### ISSUE THREAD

**Issue by ekenchan** [liudf0716/xkcptun#24]
服务端配置如下：

{
    "localinterface": "venet0:0",
    "localport": 20022,
    "remoteaddr": "127.0.0.1",
    "remoteport": 22,
    "crypt": "none",
    "mode": "fast2",
    "mtu": 1180,
    "sndwnd": 2048,
    "rcvwnd": 2048,
    "dscp": 46,
    "key": "xxx"
}

**Comment by liudf0716** [comment]
不会啊，这个我们最早就测试过，传输速率比kcptun差不了多少。

**Comment by liudf0716** [comment]
这个是测试结果，就是拿大文件测试的
https://github.com/liudf0716/xkcptun/wiki/bbr-vs-kcp-%E4%BC%98%E5%8C%96http%E4%B8%8B%E8%BD%BD%E6%80%A7%E8%83%BD%E5%AF%B9%E6%AF%94%E6%8A%A5%E5%91%8A
