### ISSUE TITLE
why start a new project named xkcptun

### ISSUE THREAD

**Issue by Mike-Strong** [liudf0716/xkcptun#25]
any diff from kcptun?
it's more popular using kcptun, and xkcptun is not  compatible with kcptun.
i use the K2 , i installed kcptun in my linux server, but i can not get connect with it because the author did not use kcptun but xkcptun.

**Comment by xicheng412** [comment]
1. You need use xkcptun in you server.
2. In most low end device, golang is slow and need much more RAM(minium 64M) to run.

**Comment by liudf0716** [comment]
@xicheng412  u are absolutly right.

**Comment by Mike-Strong** [comment]
well, need learning again
