### ISSUE TITLE
如何在搬瓦工VPS部署服务器端

### ISSUE THREAD

**Issue by heartsoarrq** [liudf0716/xkcptun#29]
路由器固件自带xkcptun，不懂服务器端如何部署，请帮忙科普下，谢谢

下边这段说明是部署方法吗？

xkcptun依赖libevent2

安装libevent2库后 (apt-get install libevent-dev)

git clone https://github.com/liudf0716/xkcptun.git

cd xkcptun

mkdir build && cd build

cmake .. (camke -DBUILD_STATIC_LINK=yes .. //静态链接)

make

生成xkcp_client, xkcp_server, xkcp_spy

**Comment by liudf0716** [comment]
这个是编译方法，编译完成后需要配置好配置服务。
