### ISSUE TITLE
Idle情况下CPU占用率过高

### ISSUE THREAD

**Issue by helloray** [liudf0716/xkcptun#36]
padavan mt7621 cpu占用一直在7~15%左右，即使没流量也是如此，这不大正常吧？配置如下
![router](https://user-images.githubusercontent.com/5954203/39614834-5c3a6c6e-4fa5-11e8-93d4-de5dce14a3c2.png)

{
        "localinterface": "lo",
        "localport": 12990,
        "remoteaddr": "xxx",
        "remoteport": 19089,
        "key": "notused",
        "crypt": "none",
        "mode": "fast3",
        "mtu": 1350,
        "sndwnd": 1024,
        "rcvwnd": 1024,
        "datashard": 10,
        "parityshard": 3,
        "dscp": 0,
        "nocomp": true,
        "acknodelay": false,
        "nodelay": 0,
        "interval": 20,
        "resend": 2,
        "nc": 1,
        "sockbuf": 4194304,
        "keepalive": 10,
}

PC上没流量cpu占用差不多也有3~5%， 这对于一个守护进程来说，没数据大部分时间应该都在休眠，即使有些周期性的计算也不至于占这么多的CPU，是哪里有问题？
![pc](https://user-images.githubusercontent.com/5954203/39614836-6359866a-4fa5-11e8-8dd8-9de738651a6b.png)

**Comment by liudf0716** [comment]
可以抓一下对应端口的数据包看看，是否有数据包进去

**Comment by helloray** [comment]
转投bbr了，看上去作者也懒得维护此项目了，关闭此问题
