### ISSUE TITLE
incompatible with kcptun-go

### ISSUE THREAD

**Issue by bettermanbao** [liudf0716/xkcptun#4]
first of all, good job, liu!

Just tested xkcp v0.4.266 on my mt7620 route, xkcp_client works perfect with xkcp_server, but when I try to use xkcp_client to connect kcptun-go server v20170329, it not works. Attached my xkcp_client config file for your reference. Let me know if you need more data. Thanks!

{
  "localinterface": "br0",
  "localport": 12580,
  "remoteaddr": "server ip",
  "remoteport": 31197,
  "key": "forfree",
  "crypt": "salsa20",
  "mode": "fast",
  "mtu": 1350,
  "sndwnd": 128,
  "rcvwnd": 128,
  "datashard": 0,
  "parityshard": 0,
  "dscp": 46,
  "nocomp": true,
  "acknodelay": false,
  "nodelay": 0,
  "interval": 20,
  "resend": 2,
  "nc": 1,
  "sockbuf": 4194304,
  "keepalive": 10
}

**Comment by liudf0716** [comment]
thanks， xkcptun does not compatible with kcptun now. cause xkcptun just release a few days, there are lots of work need to do.
