### ISSUE TITLE
kcp连接是怎么建立和关闭的？

### ISSUE THREAD

**Issue by huyuguang** [liudf0716/xkcptun#7]
看了一下代码，似乎只要用一个新的conv给对方发包，对方就直接接受了这个连接。
关闭的代码我也没看到，如果一边想要关闭kcp连接，那么它要怎么做才能通知对方让对方也关闭？
感觉像是依赖于keeplive超时？

**Comment by liudf0716** [comment]
for xkcp client side, there are no problem, causing when client close its connection, which will trigger on close event, and kcp object will be released.

for xkcp server side, u can not active close its connection which xkcp server simulated client to connect ， cause u dont know when server side you connected stop to send its data.  only after server-side close its connection, which will trigger close event and release its kcp object.

**Comment by huyuguang** [comment]
我是说，当client端调用ikcp_release，它是怎么通知server端也调用对应conv的ikcp_release的？

**Comment by liudf0716** [comment]
Client does not notify server to close its related connection.
